# CUDA_DEVICE_MAX_CONNECTIONS=1 torchrun --nproc_per_node=8 use_trainer.py --config-file ./examples/loubna/config_llama_1b.yaml
general:
  project: train
  ignore_sanity_checks: true
  run: 1b_init_60b--%j
  seed: 1234

checkpoints:
  checkpoints_path: /fsx/loubna/checkpoints/1b_init_60b
  checkpoint_interval: 2000
  resume_checkpoint_path: s3://synthetic-project-models/1b_init_60b
  checkpoints_path_is_shared_file_system: False

kill_switch_path: ./kill_1b_init_60b
lighteval: null
profiler: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
s3_upload:
  upload_s3_path: s3://synthetic-project-models/1b_init_60b
  remove_after_upload: true
  s5cmd_numworkers: 15
  s5cmd_concurrency: 6
  s5cmd_path: /fsx/nouamane/miniconda/envs/2-1-cu121/bin/s5cmd

parallelism:
  # 16 nodes
  dp: 160
  pp: 1
  tp: 1
  pp_engine: 1f1b
  tp_mode: REDUCE_SCATTER
  tp_linear_async_communication: true
  recompute_granularity: SELECTIVE

model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.022
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 2048
    initializer_range: 0.02
    intermediate_size: 8192
    # is_starcoder2_config: true
    is_llama_config: true
    max_position_embeddings: 2048
    num_attention_heads: 16
    num_hidden_layers: 24
    num_key_value_heads: 16
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_scaling: null
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 32000


tokenizer:
  tokenizer_name_or_path: "mistralai/Mistral-7B-v0.1"
  tokenizer_max_length: null
  tokenizer_revision: null

tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 4  # GBS=1.3M tokens
  sequence_length: 2048
  train_steps: 46000 # 20B tokens

optimizer:
  accumulate_grad_in_fp32: true
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 3.0e-4
    lr_decay_steps: 46000
    lr_decay_style: cosine
    lr_warmup_steps: 2000
    lr_warmup_style: linear
    min_decay_lr: 3.0e-5
  torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 0

experiment_logger:
  tensorboard_logger:
    flush_secs: 30
    tensorboard_dir: /fsx/loubna/checkpoints/logs/tensorboard/1b_init_60b
  wandb_logger:
    wandb_project: synthetic_data_models
    wandb_entity: loubnabnl

brrr_data:
  dataset:
    dataloader_type: single
    dataset_max_tokens: null
    dataset_weights: null
    datasets:
    # /fsx/synthetic_data/textbooks_20B/merged-dataset/000_textbooks_20B.ds
    - filepath: s3://synthetic-datasets-phi/tokenized_20B_textbooks/000_textbooks_20B.ds
      skip_tokens: 0
    pad_samples_to_global_batch_size: false
    skip_in_stream: true
  num_loading_workers: 1
  seed: 6



lighteval:
  batch_size: 16
  checkpoints_path: null
  generation: null
  logging:
    hub_repo_details: null
    hub_repo_results: null
    hub_repo_tensorboard: loubnabnl/debug-synthetic_model_1b_init_60b
    local_output_path: /scratch/loubna/lighteval/synthetic_model-1b_init_60b
    push_details_to_hub: null
    push_results_to_hub: null
    push_results_to_tensorboard: true
    tensorboard_metric_prefix: e
  parallelism:
    dp: 8
    pp: 1
    pp_engine: 1f1b
    recompute_granularity: null
    tp: 1
    tp_linear_async_communication: false
    tp_mode: ALL_REDUCE
  slurm_script_dir: /fsx/loubna/logs/trainings/logs_evals
  slurm_template: /fsx/loubna/projects/training/brrr/examples/loubna/run_eval.slurm.jinja
  tasks:
    custom_tasks: brrr.lighteval.custom_tasks
    dataset_loading_processes: 8
    max_samples: 1000
    multichoice_continuations_start_space: null
    no_multichoice_continuations_start_space: null
    num_fewshot_seeds: null
    tasks: early-signal
  wandb: null